from PyQt5 import QtCore, QtGui, QtWidgets
import Linear_regression as lr
import project1


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1892, 911)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.air_quality_predictor_tabWidget = QtWidgets.QTabWidget(self.frame)
        self.air_quality_predictor_tabWidget.setStyleSheet("background-image: url(:/resource.qrc/environment_img3.jpg);")
        self.air_quality_predictor_tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.air_quality_predictor_tabWidget.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.air_quality_predictor_tabWidget.setDocumentMode(False)
        self.air_quality_predictor_tabWidget.setTabsClosable(True)
        self.air_quality_predictor_tabWidget.setMovable(True)
        self.air_quality_predictor_tabWidget.setTabBarAutoHide(True)
        self.air_quality_predictor_tabWidget.setObjectName("air_quality_predictor_tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.PM25_label = QtWidgets.QLabel(self.tab)
        self.PM25_label.setGeometry(QtCore.QRect(900, 60, 51, 51))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.PM25_label.setFont(font)
        self.PM25_label.setObjectName("PM25_label")
        self.PM10_label = QtWidgets.QLabel(self.tab)
        self.PM10_label.setGeometry(QtCore.QRect(900, 120, 51, 61))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.PM10_label.setFont(font)
        self.PM10_label.setObjectName("PM10_label")
        self.NO2_label = QtWidgets.QLabel(self.tab)
        self.NO2_label.setGeometry(QtCore.QRect(910, 190, 41, 61))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.NO2_label.setFont(font)
        self.NO2_label.setObjectName("NO2_label")
        self.NH3_label = QtWidgets.QLabel(self.tab)
        self.NH3_label.setGeometry(QtCore.QRect(910, 260, 41, 51))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.NH3_label.setFont(font)
        self.NH3_label.setObjectName("NH3_label")
        self.SO2_label = QtWidgets.QLabel(self.tab)
        self.SO2_label.setGeometry(QtCore.QRect(910, 320, 41, 51))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.SO2_label.setFont(font)
        self.SO2_label.setObjectName("SO2_label")
        self.CO_label = QtWidgets.QLabel(self.tab)
        self.CO_label.setGeometry(QtCore.QRect(920, 380, 31, 51))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.CO_label.setFont(font)
        self.CO_label.setObjectName("CO_label")
        self.enter_value_label = QtWidgets.QLabel(self.tab)
        self.enter_value_label.setGeometry(QtCore.QRect(590, 10, 711, 41))
        self.enter_value_label.setSizeIncrement(QtCore.QSize(100, 0))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(20)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.enter_value_label.setFont(font)
        self.enter_value_label.setObjectName("enter_value_label")
        self.PM25_lineEdit = QtWidgets.QLineEdit(self.tab)
        self.PM25_lineEdit.setGeometry(QtCore.QRect(960, 70, 113, 31))
        self.PM25_lineEdit.setObjectName("PM25_lineEdit")
        self.PM10_lineEdit = QtWidgets.QLineEdit(self.tab)
        self.PM10_lineEdit.setGeometry(QtCore.QRect(960, 140, 113, 31))
        self.PM10_lineEdit.setObjectName("PM10_lineEdit")
        self.NO2_lineEdit = QtWidgets.QLineEdit(self.tab)
        self.NO2_lineEdit.setGeometry(QtCore.QRect(960, 210, 113, 31))
        self.NO2_lineEdit.setObjectName("NO2_lineEdit")
        self.NH3_lineEdit = QtWidgets.QLineEdit(self.tab)
        self.NH3_lineEdit.setGeometry(QtCore.QRect(960, 270, 113, 31))
        self.NH3_lineEdit.setObjectName("NH3_lineEdit")
        self.SO2_lineEdit = QtWidgets.QLineEdit(self.tab)
        self.SO2_lineEdit.setGeometry(QtCore.QRect(960, 330, 113, 31))
        self.SO2_lineEdit.setObjectName("SO2_lineEdit")
        self.CO_lineEdit = QtWidgets.QLineEdit(self.tab)
        self.CO_lineEdit.setGeometry(QtCore.QRect(960, 390, 113, 31))
        self.CO_lineEdit.setObjectName("CO_lineEdit")
        self.resultant_aqi_label = QtWidgets.QLabel(self.tab)
        self.resultant_aqi_label.setGeometry(QtCore.QRect(780, 570, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.resultant_aqi_label.setFont(font)
        self.resultant_aqi_label.setObjectName("resultant_aqi_label")
        self.submit_pushButton = QtWidgets.QPushButton(self.tab)
        self.submit_pushButton.setGeometry(QtCore.QRect(960, 500, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Open Sans Semibold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.submit_pushButton.setFont(font)
        self.submit_pushButton.setObjectName("submit_pushButton")
        self.submit_pushButton.clicked.connect(self.button_listener)
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(890, 440, 61, 51))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.OZONE_lineEdit = QtWidgets.QLineEdit(self.tab)
        self.OZONE_lineEdit.setGeometry(QtCore.QRect(960, 450, 113, 31))
        self.OZONE_lineEdit.setObjectName("OZONE_lineEdit")
        self.resultant_textEdit = QtWidgets.QTextEdit(self.tab)
        self.resultant_textEdit.setGeometry(QtCore.QRect(960, 570, 101, 31))
        self.resultant_textEdit.setObjectName("resultant_textEdit")
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setGeometry(QtCore.QRect(810, 620, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setGeometry(QtCore.QRect(760, 680, 191, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.textEdit_2 = QtWidgets.QTextEdit(self.tab)
        self.textEdit_2.setGeometry(QtCore.QRect(960, 680,511, 61))
        self.textEdit_2.setObjectName("textEdit_2")
        self.quality_textEdit = QtWidgets.QTextEdit(self.tab)
        self.quality_textEdit.setGeometry(QtCore.QRect(960, 620, 111, 41))
        self.quality_textEdit.setObjectName("quality_textEdit")
        self.suggestion_textEdit = QtWidgets.QTextEdit(self.tab)
        self.suggestion_textEdit.setGeometry(QtCore.QRect(960, 750, 511, 91))
        self.suggestion_textEdit.setObjectName("suggestion_textEdit")
        self.label_4 = QtWidgets.QLabel(self.tab)
        self.label_4.setGeometry(QtCore.QRect(810, 750, 141, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.air_quality_predictor_tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.aqi_vs_pm10 = QtWidgets.QPushButton(self.tab_2)
        self.aqi_vs_pm10.setGeometry(QtCore.QRect(900, 160, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.aqi_vs_pm10.setFont(font)
        self.aqi_vs_pm10.setObjectName("aqi_vs_pm10")
        self.aqi_vs_pm10.clicked.connect(lr.pm10_scatter_plot)
        self.aqi_vs_pm25 = QtWidgets.QPushButton(self.tab_2)
        self.aqi_vs_pm25.setGeometry(QtCore.QRect(900, 260, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.aqi_vs_pm25.setFont(font)
        self.aqi_vs_pm25.setObjectName("aqi_vs_pm25")
        self.aqi_vs_pm25.clicked.connect(lr.pm25_scatter_plot)
        self.scatter_plot_label = QtWidgets.QLabel(self.tab_2)
        self.scatter_plot_label.setGeometry(QtCore.QRect(860, 50, 231, 41))
        font = QtGui.QFont()
        font.setFamily("Nueva Std")
        font.setPointSize(20)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        font.setStrikeOut(True)
        self.scatter_plot_label.setFont(font)
        self.scatter_plot_label.setObjectName("scatter_plot_label")
        self.aqi_vs_no2 = QtWidgets.QPushButton(self.tab_2)
        self.aqi_vs_no2.setGeometry(QtCore.QRect(900, 360, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.aqi_vs_no2.setFont(font)
        self.aqi_vs_no2.setObjectName("aqi_vs_no2")
        self.aqi_vs_no2.clicked.connect(lr.no2_scatter_plot)
        self.aqi_vs_nh3 = QtWidgets.QPushButton(self.tab_2)
        self.aqi_vs_nh3.setGeometry(QtCore.QRect(900, 460, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.aqi_vs_nh3.setFont(font)
        self.aqi_vs_nh3.setObjectName("aqi_vs_nh3")
        self.aqi_vs_nh3.clicked.connect(lr.nh3_scatter_plot)
        self.aqi_vs_co = QtWidgets.QPushButton(self.tab_2)
        self.aqi_vs_co.setGeometry(QtCore.QRect(900, 660, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.aqi_vs_co.setFont(font)
        self.aqi_vs_co.setObjectName("aqi_vs_co")
        self.aqi_vs_co.clicked.connect(lr.co_scatter_plot)
        self.aqi_vs_so2 = QtWidgets.QPushButton(self.tab_2)
        self.aqi_vs_so2.setGeometry(QtCore.QRect(900, 560, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.aqi_vs_so2.setFont(font)
        self.aqi_vs_so2.setObjectName("aqi_vs_so2")
        self.aqi_vs_so2.clicked.connect(lr.so2_scatter_plot)
        self.aqi_vs_o3 = QtWidgets.QPushButton(self.tab_2)
        self.aqi_vs_o3.setGeometry(QtCore.QRect(900, 760, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.aqi_vs_o3.setFont(font)
        self.aqi_vs_o3.setObjectName("aqi_vs_o3")
        self.aqi_vs_o3.clicked.connect(lr.ozone_scatter_plot)
        self.aqi_vs_parameters = QtWidgets.QPushButton(self.tab_2)
        self.aqi_vs_parameters.setGeometry(QtCore.QRect(800,850,400,41))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.aqi_vs_parameters.setFont(font)
        self.aqi_vs_parameters.setObjectName("aqi_vs_parameters")
        self.aqi_vs_parameters.clicked.connect(lr.parameters_scatter_plot)
        self.air_quality_predictor_tabWidget.addTab(self.tab_2, "")
        self.gridLayout_2.addWidget(self.air_quality_predictor_tabWidget, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.air_quality_predictor_tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "AQI PREDICTOR"))
        self.PM25_label.setText(_translate("MainWindow", "PM2.5"))
        self.PM10_label.setText(_translate("MainWindow", "PM10"))
        self.NO2_label.setText(_translate("MainWindow", "NO2"))
        self.NH3_label.setText(_translate("MainWindow", "NH3"))
        self.SO2_label.setText(_translate("MainWindow", "SO2"))
        self.CO_label.setText(_translate("MainWindow", "CO"))
        self.enter_value_label.setText(_translate("MainWindow", "     Enter the values of each to predict AQI   "))
        self.resultant_aqi_label.setText(_translate("MainWindow", "RESULTANT AQI"))
        self.submit_pushButton.setText(_translate("MainWindow", "SUBMIT"))
        self.label.setText(_translate("MainWindow", "OZONE"))
        self.label_2.setText(_translate("MainWindow", "AIR QUALITY"))
        self.label_3.setText(_translate("MainWindow", "HEALTH MESSAGE"))
        self.label_4.setText(_translate("MainWindow", "SUGGESTION"))
        self.air_quality_predictor_tabWidget.setTabText(self.air_quality_predictor_tabWidget.indexOf(self.tab), _translate("MainWindow", "Air Quality Predictor"))
        self.aqi_vs_pm10.setText(_translate("MainWindow", "AQI VS PM10"))
        self.aqi_vs_pm25.setText(_translate("MainWindow", "AQI VS PM2.5"))
        self.scatter_plot_label.setText(_translate("MainWindow", "SCATTER PLOTS"))
        self.aqi_vs_no2.setText(_translate("MainWindow", "AQI VS NO2"))
        self.aqi_vs_nh3.setText(_translate("MainWindow", "AQI VS NH3"))
        self.aqi_vs_co.setText(_translate("MainWindow", "AQI VS CO"))
        self.aqi_vs_so2.setText(_translate("MainWindow", "AQI VS SO2"))
        self.aqi_vs_o3.setText(_translate("MainWindow", "AQI VS O3"))
        self.aqi_vs_parameters.setText(_translate("MainWindow", "AQI VS PM2.5,PM10,NO2,NH3,SO2,CO,OZONE"))
        self.air_quality_predictor_tabWidget.setTabText(self.air_quality_predictor_tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Data Analysis"))

    def button_listener(self):
        try:
            PM25_value = float(self.PM25_lineEdit.text())
            PM10_value = float(self.PM10_lineEdit.text())
            NO2_value = float(self.NO2_lineEdit.text())
            NH3_value = float(self.NH3_lineEdit.text())
            SO2_value = float(self.SO2_lineEdit.text())
            CO_value = float(self.CO_lineEdit.text())
            OZONE_value = float(self.OZONE_lineEdit.text())
            large = 0
            pre_dominant_factor = None
            if(PM25_value>large):
                large = PM25_value
                pre_dominant_factor = 'PM2.5'
            if(PM10_value>large):
                large = PM10_value
                pre_dominant_factor = 'PM10'
            if(NO2_value>large):
                large = NO2_value
                pre_dominant_factor = 'NO2'
            if(NH3_value>large):
                large = NH3_value
                pre_dominant_factor = 'NH3'
            if(SO2_value>large):
                large = SO2_value
                pre_dominant_factor = 'SO2'
            if(CO_value>large):
                large = CO_value
                pre_dominant_factor = 'CO'
            if(OZONE_value>large):
                large = OZONE_value
                pre_dominant_factor = 'OZONE'
            print("The largest value among all pollutants is:", large)
            print("The pre-dominant factor is: ", pre_dominant_factor)
            aqi = lr.user_aqi_predictor(PM25_value,PM10_value,NO2_value,NH3_value,SO2_value,CO_value,OZONE_value)
            print(int(aqi))
            self.resultant_textEdit.setText(str(aqi))
            quality, message = lr.call_functions(int(aqi))
            print(quality)
            print(message)
            self.quality_textEdit.setText(quality)
            self.textEdit_2.setText(message)
            if(pre_dominant_factor=='PM2.5'):
                self.suggestion_textEdit.setText("Stop smoking, Mulch garden waste instead of burning it, Limit the use of fireplaces and wood stoves, Take action to reduce wildfires, Reduce diesel emissions by replacing older engines with newer and cleaner ones. This will help to reduce the PM2.5")
            elif(pre_dominant_factor=='PM10'):
                self.suggestion_textEdit.setText("Reduce vehicular emission by taking steps like odd even, reduce industrial, commercial and residential combustion, construction activities should be ceased for some period of time. This will help to reduce the PM10")
            elif(pre_dominant_factor=='NO2'):
                self.suggestion_textEdit.setText("Reduce burning of fossil fuels, biomass and high temperature combustion processess. This will help to reduce the NO2")
            elif(pre_dominant_factor=='NH3'):
                self.suggestion_textEdit.setText("The largest source of NH3 emissions is agriculture, including animal husbandry and NH3-based fertilizer applications so start monitoring it. The other sources includes industrial processes, vehicular emissions so reduce these processes will help in reducing NH3")
            elif(pre_dominant_factor=='SO2'):
                self.suggestion_textEdit.setText("Reduce Burning of fossil fuels, metal smelting, petroleum refining etc. to minimise the SO2 pollutant")
            elif(pre_dominant_factor=='OZONE'):
                self.suggestion_textEdit.setText("Hydrocarbons and NOX upon reacting with sunlight results in O3 formation hence high NO2 in air will automatically lead to ozone formation.Reduce burning of fossil fuels, biomass and high temperature combustion processess") 
            elif(pre_dominant_factor=='CO'):
                self.suggestion_textEdit.setText(" Reduce burning of carbonaceus fuels, emission from IC engines")
        except ValueError:
            print("Please enter all the values")



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
